### ISSUE TITLE
Expose metrics even when a node is down

### ISSUE THREAD

**Issue by babolivier** [gesellix/couchdb-prometheus-exporter#10]
I work with a CouchDB cluster which currently contains 3 nodes. When I stop one of them and send a `GET` request to the exporter, no CouchDB-related metrics can be seen, and the following error can be found in the exporter's logs:

```
Error collecting stats: Error reading couchdb stats: Error reading couchdb stats: Status 412 Precondition Failed (412): {"error":"nodedown","reason":"[node name] is down"}
```

This means that, for example, if we update our cluster by removing a node but fail to do it properly (so that CouchDB still thinks that node exists), the exporter won't expose any data on the rest of the cluster for some time (actually I just noticed we don't have any data for the whole cluster for at least a few hours during a week-end a couple of weeks ago).

In these cases, I'd expect the exporter to log the error but still expose data about the other nodes. What do you think about this?

**Comment by gesellix** [comment]
Thanks for the PR, that helps a lot!

What do you think about adding a label `node` for the metric `up`, so that one could also monitor the availability of each node?

**Comment by babolivier** [comment]
User-wise, it would be an appreciated improvement I think. I'll look into it as soon as I find some time for this.

**Comment by gesellix** [comment]
great, thanks!
