### ISSUE TITLE
adding changes_pending metric from _active_tasks endpoint

### ISSUE THREAD

**Issue by sangeethdba** [gesellix/couchdb-prometheus-exporter#110]
it would be greatfull to have a metric that covers changes_pending  from _active_task couchdb endpoint.

we always  got a good overview replication status based on this metric. would you please see the possibility of adding this metric.

{
      "node":"couchdb@XXXXXXX,
      "pid":"<0.10890.109>",
      "changes_pending":null,   <--------- this atribute.
      "checkpoint_interval":5000,
     ......
}

let me know if there is a metric that is covering this already.

thanks agian.

**Comment by sangeethdba** [comment]
@gesellix ^^^

**Comment by gesellix** [comment]
This attribute currently isn't exposed as metric. Do you think you could provide a pull request?

**Comment by sangeethdba** [comment]
I'm not a good go developer and I will see if I can find a developer who
can contribute.

**Comment by gesellix** [comment]
Alright, no pressure. I can have a look into it at the beginning of February.

**Comment by sangeethdba** [comment]
Thank you so much

**Comment by gesellix** [comment]
Note to self: [/_active_tasks](https://docs.couchdb.org/en/latest/api/server/common.html#active-tasks), [/_scheduler/jobs](https://docs.couchdb.org/en/latest/api/server/common.html#scheduler-jobs), and [/_scheduler/docs](https://docs.couchdb.org/en/latest/api/server/common.html#scheduler-docs) have overlapping content. We have to decide how to choose the best of them (probably depending on the actual CouchDB api version), or how to merge content into single metrics. Maybe we don't even merge, but be explicit about the different data sources by providing different metrics.

**Comment by gesellix** [comment]
I've just released [30.2.0](https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v30.2.0) with a new metric `active_tasks_replication_changes_pending` based on the field from the `/_active_tasks` endpoint. Please give it a try and leave some feedback here. I'm closing this issue now, but feel free to re-open in case anything doesn't work for your setup.

Thanks for your suggestion!

**Comment by sangeethdba** [comment]
i can see couchdb_server_active_tasks_replication_changes_pending{continuous="true",doc_id="xxxx",node_name="couchdb",source="https://ixxxxx/item_store-172/",target="http://localhost:5984/item_store-172/"} 507740

**Comment by gesellix** [comment]
Ah, my bad, I didn't include the subsystem in the mentioned metric name. You're right, that's the correct metric name, just "beside" `couchdb_server_active_tasks_replication_updated_on`.

So, I'll update the release notes, thanks for keeping me updated! :)

In case anything isn't working as expected, feel free to submit another issue.
