### ISSUE TITLE
Metrics on stopped nodes showing up

### ISSUE THREAD

**Issue by babolivier** [gesellix/couchdb-prometheus-exporter#14]
We noticed in our graphs that we have some metrics showing up about nodes that have been stopped.

Earlier today, a colleague of mine was stopping a couple of nodes in our sandbox environment and I could witness that, even though `/_membership` was only returning the only one node still up, a `curl` request on the exporter would still show metrics about the other two (which were down). These disappeared when I restarted the exporter. 

To me, there's at least two possible explanations to this:

* There's some caching somewhere
* Although the series about the nodes that are down aren't updated, they still exist and need to be removed/set to a special value when the node isn't listed by CouchDB's `/_membership` endpoint

The second one would seem the obvious one to me, though.

What do you think?

**Comment by gesellix** [comment]
Exciting - I'm not aware of any caching, so I also tend to agree to your second explanation. It seems I'll have to learn a bit more about the prometheus client and how it handles "non-updated" entries.

I guess your PR adding the `node_up` metric will be helpful in that regard.

**Comment by gesellix** [comment]
With #13 being merged we can probably try to reproduce this issue more easily.

@babolivier have you stumbled over this behaviour in your setup again?

**Comment by gesellix** [comment]
I can confirm that old Gauges' values are kept for the lifetime of the CouchDB exporter. I'm currently trying to find a way of resetting them.

**Comment by gesellix** [comment]
Thank you very much for filing this issue! I assume to have fixed it, please give the release https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/13 a try.

**Comment by babolivier** [comment]
Awesome, will do!

**Comment by babolivier** [comment]
Hey @gesellix, I had the time to do a few tests on our cluster with the new release, and it works perfectly fine: as soon as I remove a node from the cluster, the metrics related to the said nodes disappear from the exporter's response :) Thanks!

**Comment by gesellix** [comment]
Thanks @babolivier for testing and leaving your feedback here! :)
