### ISSUE TITLE
Exporting data from app db to prometheus (not only stats)

### ISSUE THREAD

**Issue by delkant** [gesellix/couchdb-prometheus-exporter#21]
I would like to export data to prometheus from my app's database which is a CouchDB db. How can I accomplish that?

Thanks.

**Comment by gesellix** [comment]
I guess I don't fully understand what you're aiming at. Exporting documents from a CouchDB is not what this Prometheus exporter is aiming at. Exporting documents is possible via [HTTP/JSON api](http://docs.couchdb.org/en/stable/api/document/index.html), but depending on your actual purpose for the exported data you can probably find ready-to-run tools on the internet.

The couchdb-prometheus-exporter provided in this repository only "exports" metrics in a Prometheus specific format by calling e.g. the [_stats](http://docs.couchdb.org/en/stable/api/server/common.html#stats) endpoint of a CouchDB. It doesn't export documents.

**Comment by delkant** [comment]
Thanks.
