### ISSUE TITLE
No Stats when using _stats

### ISSUE THREAD

**Issue by coop59** [gesellix/couchdb-prometheus-exporter#26]
Hello Guys,

So I installed this using the following:
docker run -d --name hostname --label triton.network.public="SDC-PCI-Dev-DB" -p 9984:9984 gesellix/couchdb-prometheus-exporter -couchdb.uri=http://xxx.xxx.xxx.xxx:8091 -couchdb.username=admin -couchdb.password=admin_pwd
````
It works but not getting the metrics I expected when I visit the url
http://xxx.xxx.xxx.xxx/_stats it goes to this http://xxx.xxx.xxx.xxxx/metrics. 

What am I doing wrong, the following are the only metrics I am getting with this:

````
-> HELP couchdb_httpd_up Was the last query of CouchDB stats successful.
-> TYPE couchdb_httpd_up gauge
couchdb_httpd_up 0
-> HELP go_gc_duration_seconds A summary of the GC invocation durations.
-> TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000163025
go_gc_duration_seconds{quantile="0.25"} 0.000163025
go_gc_duration_seconds{quantile="0.5"} 0.001001657
go_gc_duration_seconds{quantile="0.75"} 0.001001657
go_gc_duration_seconds{quantile="1"} 0.001001657
go_gc_duration_seconds_sum 0.001164682
go_gc_duration_seconds_count 2
-> HELP go_goroutines Number of goroutines that currently exist.
-> TYPE go_goroutines gauge
go_goroutines 10
-> HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
-> TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.18948e+06
-> HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
-> TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.872344e+06
-> HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
-> TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.443446e+06
-> HELP go_memstats_frees_total Total number of frees.
-> TYPE go_memstats_frees_total counter
go_memstats_frees_total 11054
-> HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
-> TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 4382
-> HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
-> TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 3.18948e+06
-> HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
-> TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 2.064384e+06
-> HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
-> TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 4.227072e+06
-> HELP go_memstats_heap_objects Number of allocated objects.
-> TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 6790
-> HELP go_memstats_heap_released_bytes_total Total number of heap bytes released to OS.
-> TYPE go_memstats_heap_released_bytes_total counter
go_memstats_heap_released_bytes_total 0
-> HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
-> TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.291456e+06
-> HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage       ->collection.
-> TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.5345130942674613e+09
-> HELP go_memstats_lookups_total Total number of pointer lookups.
-> TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 42
-> HELP go_memstats_mallocs_total Total number of mallocs.
-> TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 17844
-> HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
-> TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 152768
-> HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
-> TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 163840
-> HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
-> TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 37848
-> HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
-> TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 49152
-> HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
-> TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 6.013728e+06
-> HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
-> TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.417858e+06
-> HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
-> TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.048576e+06
-> HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
-> TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.048576e+06
-> HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
 TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.08526e+07
-> HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
-> TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.37
-> HELP process_max_fds Maximum number of open file descriptors.
-> TYPE process_max_fds gauge
process_max_fds -1
-> HELP process_open_fds Number of open file descriptors.
-> TYPE process_open_fds gauge
process_open_fds 11
-> HELP process_resident_memory_bytes Resident memory size in bytes.
-> TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.3668352e+07
-> HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
-> TYPE process_start_time_seconds gauge
process_start_time_seconds 1.53451295881e+09
-> HELP process_virtual_memory_bytes Virtual memory size in bytes.
-> TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.579008e+07
````

Please help I need to get this working we have a 6 node CouchDB Cluster

Thanks,
Michael

**Comment by gesellix** [comment]
Is the `-couchdb.uri=http://xxx.xxx.xxx.xxx:8091` the correct address for your CouchDB instance?

To clarify: the `/_stats` endpoint is the CouchDB's endpoint to retrieve some stats, but the CouchDB-Prometheus-Exporter (which internally uses the _stats endpoint) is available at `/metrics`.

**Comment by gesellix** [comment]
@coop59 I'm going to close this issue. In case you still encounter problems, please leave a note and/or re-open the issue. Thanks!

**Comment by coop59** [comment]
Yeah thats fine sorry I though askes you to that, my bad.
