### ISSUE TITLE
Binary Builds?

### ISSUE THREAD

**Issue by dphilpot** [gesellix/couchdb-prometheus-exporter#56]
Hey,

since i have no idea of "go" or how to build this kind of stuff, i would love to see some binary pre-builds of this project. Further i would suggest having multiple environment builds since not everyone is able to run you exporter in a docker-container.

Hope you find the time for this.

Regards,

Dennis

**Comment by gesellix** [comment]
Hi @dphilpot,

thanks for your suggestion, that's something I can certainly do using GitHub's releases. I'll look into it soon, but probably not during the holidays. If you already have a small example in another project, I could copy & paste its solution - just leave a link here, that would certainly make things faster for me :)

Best,
Tobias

**Comment by gesellix** [comment]
Note to self: give https://goreleaser.com/ a try.

**Comment by dphilpot** [comment]
Hey @gesellix,

thanks for taking credit of this suggestion, as far as i can tell almost every go prometheus exporter got their binaries compiled, for example:

https://github.com/prometheus/node_exporter
https://github.com/prometheus/haproxy_exporter

**Comment by gesellix** [comment]
Another note to self: the Prometheus developers use a tool "promu" for their release process, see https://github.com/prometheus/promu/blob/master/cmd/release.go for the actual code.

**Comment by gesellix** [comment]
I've started working on it in #57

**Comment by gesellix** [comment]
Hey @dphilpot, you can find the first automated release including ready-build binaries at https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v27.0.0 (as of #60).

If you're missing a platform or in case something's not working as expected, please file another issue.

Thanks a lot for your patience!
