### ISSUE TITLE
prometheus can't scrape exporter

### ISSUE THREAD

**Issue by m1cka** [gesellix/couchdb-prometheus-exporter#62]
prometheus config
    - job_name: 'couchdb-exporter'
        scrape_interval: 10s
        static_configs:
          - labels:
              instance: couch-db1
            targets:
              - "192.168.1.100:9984"

docker-compose
services:
  couchdbstats_1:
    image: "gesellix/couchdb-prometheus-exporter:latest"
    command: --couchdb.uri=http://192.168.1.100:5984 --logtostderr
    env_file: .couchdb-env
    ports:
      - "9984:9984"

prometheus web target status down
endpoint  http://192.168.1.100:9984/metrics
Error Get http://192.168.1.100:9984/metrics: context deadline exceeded

**Comment by m1cka** [comment]
domainname: mydomain.com
environment:
- COUCHDB.URI=http://couchdb1.mydomain.com:5984
- COUCHDB.USERNAME=admin
- COUCHDB.PASSWORD=mypassword

**Comment by gesellix** [comment]
Is this still an issue, maybe with the docs?
