### ISSUE TITLE
Invalid Environment variable names

### ISSUE THREAD

**Issue by schferbe** [gesellix/couchdb-prometheus-exporter#67]
I am trying to run `couchdb-prometheus-exporter` with a `systemd` service file. I want to set the Environment variables there so that they don't show up in `ps aux`. However the `.` in the variable names is not supported by `systemd` or `bash`. E.g. I get:

```
/etc/systemd/system/my.service:6: Invalid environment assignment, ignoring: TELEMETRY.ADDRESS=localhost:9985
```

As an alternative I would use a config file, but I could not find a specification of the format (ini, yml?). 

Please give me a pointer how to specify the CLI parameters on a different way. 

Also you might like to change the Environment variables to usable names like TELEMETRY_ADDRESS.

**Comment by gesellix** [comment]
Seems like I'll have to add the variant with underscores `_`, like you suggested :)

For the time being, please see the example at https://github.com/gesellix/couchdb-prometheus-exporter/issues/3#issuecomment-302900545 using the `env` cli tool. I'm not sure if that's going to work in a `*.service` file.

I would recommend a config file, though. Regarding your question about the file format: it currently uses .properties format like the one at https://github.com/gesellix/couchdb-prometheus-exporter/blob/b99fdce4ca6f028806d95d50249741b38080f191/examples/stack/config.properties
Would that help?

**Comment by schferbe** [comment]
That is a good solution to my problem. Thank you. But you could keep this issue open for the `_` variants.

**Comment by gesellix** [comment]
Underscores will be allowed with #68
