### ISSUE TITLE
[glog issue?] usage of log_dir flag along w/ alsologtostderr flag

### ISSUE THREAD

**Issue by xft843** [gesellix/couchdb-prometheus-exporter#7]
Previously, I used to used to use '-log_dir' flag along with  when calling couchdb-exporter to indicate where the log file should be located, however, with the addition of the "couchdb-exporter-glog.go" file it seems like the flag is not passed onto glog correctly. 

Example of previous cmd: 
/bin/couchdb-exporter -telemetry.address=0.0.0.0:9090 -couchdb.uri=${PROTOCOL}://${COREOS_IP}:5984 -alsologtostderr -log_dir /opt/couchdb-exporter/logs

How do I go about adding this functionality of having a log file w/ logs in addition to stderr logging? Is there already a way currently, or must I make changes to "couchdb-exporter-glog.go" file in order to enable this?

**Comment by gesellix** [comment]
I'll have to check, but chances are high that I accidentally dropped that option. If you like you can certainly try to fix it yourself, I would appreciate a pull request!

**Comment by gesellix** [comment]
Note to self: the issue might have been introduced with PR #3 (relevant commit: https://github.com/gesellix/couchdb-prometheus-exporter/commit/742480c6952b1ed3d131188d4c4ad10f2ec9f593).

**Comment by gesellix** [comment]
@xft843 Can you check whether the expected log appear in your operating system's tmp directory?

**Comment by gesellix** [comment]
@xft843 please give the current version a try. It has also been tagged as release `3`, while the relevant commit is https://github.com/gesellix/couchdb-prometheus-exporter/commit/34930d88aaf013440e04ee79408d84b650338282.

**Comment by gesellix** [comment]
"Works on my machine", closing. Feel free to re-open in case it doesn't work in your environment!
