### ISSUE TITLE
Error in unmarhsall when fetching database details

### ISSUE THREAD

**Issue by skeyby** [gesellix/couchdb-prometheus-exporter#80]
I tried to configure the exporter to fetch datas about _users database, now when I ping metrics I get:

Error collecting stats: error collecting couchdb stats: error unmarshalling database '_users' stats: json: invalid number literal, trying to unmarshal "\"578002-g1AAAAGLeJzLYWBg4MhgTmEQTc4vTc5ISXIwNNAzNDYGYgs9I_McoDRTHguQZHgApP4DQVYSA6OkMFFaDkC03AdpkbpKlJYFEC37wVoCiNLSANEyH6RFOp2AlqQEIJlUD_WH-FRCyh1AyuOhyqU2ElKuAFJuD1P-gIDyRIYkeahaad4sAFn-ae4\"" into Number

I guess it's the seq for the replication popping up somewhere...

**Comment by gesellix** [comment]
Can you tell me whether you used a released version or if you compiled the exporter locally with a Golang version 1.14+?

**Comment by skeyby** [comment]
I compiled locally, can’t tell you the go version now but it’s latest available on FreeBSD.

I used the instructions in the readme 

Inviato da iPhone

**Comment by gesellix** [comment]
Alright, I assume you're probably working with Golang 1.14+ (you can find out in your shell via `go version`), which indeed has issues with the current codebase. I'm working on a fix at #83.

**Comment by gesellix** [comment]
Released with https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v29.2.0 this one shouldn't happen anymore. Building locally should also work with all Golang versions of 1.13+.
Thanks for reporting the issue!

**Comment by skeyby** [comment]
> Alright, I assume you're probably working with Golang 1.14+ (you can find out in your shell via `go version`), which indeed has issues with the current codebase. I'm working on a fix at #83.

I confirm your assumption:

go-1.14.9,1                    Go programming language

Thanks, I'll try the fix in a few minutes

**Comment by skeyby** [comment]
@gesellix Maybe I'm doing something wrong, but the error seems to be still there:

E1006 09:05:45.479631   72791 collector.go:392] Error collecting stats: error collecting couchdb stats: error unmarshalling database 'documents' stats: json: invalid number literal, trying to unmarshal "\"1206803-g1AAAAGLeJzLYWBg4MhgTmEQTc4vTc5ISXIwNNAzNDYGYgs9I_McoDRTHguQZHgApP4DQVYSA5PhKqK0HIBouQ_SElhFlJYFEC37QVr8W4nS0gDRMh-spYiAlqQEIJlUD_VHwD9Cyh1AyuOhygNlCSlXACm3hyoPZSegPJEhSR7mkmtZAM2sa88\"" into Number

I deleted the binary and all go directories, redid "go get github.com/gesellix/couchdb-prometheus-exporter"

It downloaded everything from GitHub back again and recompiled it.

Unfortunately the reported version is always "dev".

**Comment by skeyby** [comment]
I can confirm the error is gone, thanks.👌🏻
